name: Convox Deploy
description: Build and Deploy a Convox app in a single step
author: Convox
branding:
  icon: upload-cloud
  color: blue
inputs:
  rack:
    description: Convox Rack name
    required: true
  app:
    description: Convox app name
    required: true
  password:
    description: Convox deploy key value
    required: false
  host:
    description: Convox Console host address
    required: false
    default: console.convox.com
  description:
    description: Convox build description
    required: false
  cached:
    description: Whether to utilise the docker cache during the build
    required: false
    default: true
  manifest:
    description: Use a custom path for your convox.yml
    required: false
  buildargs:
    description: Custom build arguments for the Docker build
    required: false
runs:
  using: docker
  image: Dockerfile
